### ISSUE TITLE
Support react v18

### ISSUE THREAD

**Issue by 100terres** [react-forked/dnd#293]
Everything that need to be done in order to support react v18 will be tracked in this issue. You can also have a look at the [React v18 milestone](https://github.com/react-forked/dnd/milestone/2).

We are in the early stage of the investigation, so the list is not yet exhaustive. New issue will be added as we discover them.

**Must have**

- [x] https://github.com/react-forked/dnd/issues/319
- [x] https://github.com/react-forked/dnd/issues/318
- [x] https://github.com/react-forked/dnd/issues/320
- [x] https://github.com/react-forked/dnd/issues/317

**Nice to have**

- [ ] https://github.com/react-forked/dnd/issues/393

**Comment by antoinejaussoin** [comment]
Yes please!!

**Comment by 100terres** [comment]
The work is in progress. I'll try to have something working in the upcoming as soon as possible :slightly_smiling_face:

**Comment by antoinejaussoin** [comment]
That's awesome, thanks for the work!! Let me know if I can help with testing in a real-world project.

**Comment by jacokok** [comment]
Would this include support for strict mode or should we create a new issue for that.

Currently using <React.StrictMode> with react 18 is not working.

**Comment by 100terres** [comment]
> Would this include support for strict mode or should we create a new issue for that.

@jacokok it feels like something we'll investigate separately. I'll open a new issue to see how we could support [strict mode](https://reactjs.org/docs/strict-mode.html).

**Comment by 100terres** [comment]
@jacokok I've updated the description of the issue to be include strict mode support.

**Comment by antoinejaussoin** [comment]
> Would this include support for strict mode or should we create a new issue for that.
> 
> Currently using <React.StrictMode> with react 18 is not working.

Actually that was mainly what I was interested in. Good luck with the work!

**Comment by 100terres** [comment]
The migration from `Enzyme` to `@testing-library/react` is going well. There is only one file to refactor. You can follow the progress here: https://github.com/react-forked/dnd/pull/323

I'll work on [Run test suite for react v16, v17 and v18](https://github.com/react-forked/dnd/issues/320) real soon :slightly_smiling_face:

**Comment by 100terres** [comment]
The [migration from Enzyme to @testing-library/react](https://github.com/react-forked/dnd/pull/323) is done :heavy_check_mark:

Next step: [Run test suite for react v16, v17 and v18](https://github.com/react-forked/dnd/issues/320) :slightly_smiling_face:

**Comment by Domino987** [comment]
Any news on this 🙂 we are blocked with our upgrading to react 18🙉

**Comment by Toshinaki** [comment]
It's been a while. Any progress on this?🙂

**Comment by AlimovSV** [comment]
Any news?

**Comment by AntonOfTheWoods** [comment]
Pretty the only reasonable choice is for one of us lurkers to finish the work here, or move to react-dnd...

**Comment by jacokok** [comment]
> dnd-kit does not support touch. So no option

I tested it and it did support touch I am pretty sure. The issue I found was it also does not work in react strict mode yet. (So I did not want to migrate and just have the same issue)

> I think if someone had the ability to do this, it would have been done by now.

It would be interesting to see if dnd-kit can solve the strict mode problem.

For now it will be amazing if we could get a beta release of this package with the react 18 packages fix so we can stop running npm --force

**Comment by Toshinaki** [comment]
> > dnd-kit does not support touch. So no option
> 
> I tested it and it did support touch I am pretty sure. The issue I found was it also does not work in react strict mode yet. (So I did not want to migrate and just have the same issue)
> 
> > I think if someone had the ability to do this, it would have been done by now.
> 
> It would be interesting to see if dnd-kit can solve the strict mode problem.
> 
> For now it will be amazing if we could get a beta release of this package with the react 18 packages fix so we can stop running npm --force

Well, I'm in strict mode and using dnd-kit without any problem; no console warnings and everything worked.

What's the issue you found?

**Comment by jacokok** [comment]
> What's the issue you found?

Honestly I did not test it with strict mode because I saw this issue.
https://github.com/clauderic/dnd-kit/issues/775

**Comment by AntonOfTheWoods** [comment]
@Toshinaki , the issue https://github.com/clauderic/dnd-kit/issues/775 is exactly the same as everyone (maybe except react-dnd?) on React 18. There are open issues, maintainer says "I'll get on to it", then nothing for many months. Obviously others aren't quite as bad as this repo in terms of silence from the maintainer but one of us is going to have to take responsibility here...

**Comment by Toshinaki** [comment]
@AntonOfTheWoods 
I'm not interested in arguing about responsibility or something here. But I'm waiting for my dinner so I can explain myself a bit.

Some people like me don't care about what we use, but just want to get the work done.
For my personal project, I was using react-beautiful-dnd and bothered with [this issue](https://github.com/atlassian/react-beautiful-dnd/issues/2407), and [this](https://github.com/atlassian/react-beautiful-dnd/issues/2350) directed me here.

I asked for progress, but got no response. So I quitted waiting.
I found dnd-kit, and it worked for my purpose, no errors nor warnings, so I recommended.
End of the story.

It works for you, great, use it; not working? idc

I appreciate🧡 this and other open source great works, and that's all.

**Comment by AntonOfTheWoods** [comment]
@Toshinaki , ok, sorry I missed that it's a drop-in replacement. That is very interesting! Having to reimplement most of the logic can make moving to another lib a massive hassle but if dnd-kit is just point to the new lib and "It Works!", then that is definitely awesome, thanks!

**Comment by jacokok** [comment]
> @Toshinaki , ok, sorry I missed that it's a drop-in replacement. That is very interesting! Having to reimplement most of the logic can make moving to another lib a massive hassle but if dnd-kit is just point to the new lib and "It Works!", then that is definitely awesome, thanks!

I migrated to dnd-kit. It was not a drop in replacement. It took me a bit longer than anticipated, but works really well.

Check out this comment https://github.com/atlassian/react-beautiful-dnd/issues/2399#issuecomment-1167427762 on getting this lib to work with strict mode.

**Comment by babbittw-techsmith** [comment]
> I migrated to dnd-kit. It was not a drop in replacement. It took me a bit longer than anticipated, but works really well.

Im trying to do the same now and struggling with getting click events to work with dnd-kit. Any chance you managed to do that?

**Comment by 100terres** [comment]
Sorry for keeping you all waiting! :grimacing: I'm still trying to find the time to make it work, but as many of you might have notice it's not an easy fix... and it will take a lot of my free time (outside of work) to support react v18.

I still plan on making it work in the upcoming months, because I need this for a personal project and for work. But if you are in a rush to migrate your codebase to react v18 then I would suggest to not wait for react-forked/dnd to support the latest version of react and move to another library.

If anyone has the time to to do all the refactoring needed I'll be more then happy to review your pull request!

Sorry again and I hope you understand.

**Comment by Xhale1** [comment]
@100terres I'm using `react-beautiful-dnd` for a few projects that required react 18 and I wasn't sure how progress was coming along so I forked your work and released [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) which supports react 18 and strict mode.

It would never have been possible without your truly amazing work on the original `react-beautiful-dnd`

We needed our own fork so we could develop new features with a semi-regular cadence, and I intend to further develop the library there.

**Comment by AntonOfTheWoods** [comment]
> @100terres I'm using `react-beautiful-dnd` for a few projects that required react 18 and I wasn't sure how progress was coming along so I forked your work and released [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) which supports react 18 and strict mode.
> 
> We needed our own fork so we could develop new features with a semi-regular cadence, and I intend to further develop the library there.
> 
> It would never have been possible without your truly amazing work on the original `react-beautiful-dnd`. I cannot thank you enough for what you've accomplished here. And no worries on being caught up with life stuff, you don't owe anyone anything. I've certainly left some github issues open for much longer than I'd like before, it happens.

It would have saved me a couple of very annoying days of work if you had posted about this work a couple of weeks ago!

**Comment by Xhale1** [comment]
> It would have saved me a couple of very annoying days of work if you had posted about this work a couple of weeks ago!

Haha, timing could have been a bit better. Did you end up migrating to dnd kit? If so how do you like it compared to react beautiful dnd?

**Comment by caleb531** [comment]
Hi all,

I've been watching this issue closely, and I would just like to add a few thoughts:

I am using react-beautiful-dnd for one of my projects, and maybe the most important reason I chose it is how natural the interactivity feels. This is best explained in Alex Reardon's [blog post that introduces the library](https://medium.com/@alexandereardon/rethinking-drag-and-drop-d9f5770b4e6b):

> In react-beautiful-dnd a dragging item's impact is based on its centre of gravity — regardless of where a user grabs an item from. A dragging items impact follows similar rules to a set of scales ⚖️.

This is a mechanic I feel like most other DND libraries get wrong, and something that's largely unique to RBDND. However, it seems that dnd-kit also implements the same behavior, if you [play with their examples](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-multiple-containers--basic-setup). So I am encouraged in that respect, in that I might be able to switch to dnd-kit without sacrificing a natural UX.

Of course, it would be great to see react-forked/dnd gain React 18 support, but in the interim, dnd-kit may prove to be a worthy alternative.

**Comment by Xhale1** [comment]
> Of course, it would be great to see react-forked/dnd gain React 18 support, but in the interim, dnd-kit may prove to be a worthy alternative.

@caleb531 I created a fork of this which supports react 18 (it's like two comments up 🙂)

@hello-pangea/dnd

https://github.com/hello-pangea/dnd

**Comment by AntonOfTheWoods** [comment]
> Haha, timing could have been a bit better. Did you end up migrating to dnd kit? If so how do you like it compared to react beautiful dnd?
@Xhale1 react-dnd. I found examples pretty close to what I needed so just went with that. I also found that the touch version actually works fine for the browsers I need on the desktop, so that made things a little simpler. I haven't actually pushed to prod yet though so might even just bite the bullet on that if yours works out of the box migrating from react-beautiful-dnd!

**Comment by 100terres** [comment]
Hi @Xhale1

> I'm using react-beautiful-dnd for a few projects that required react 18 and I wasn't sure how progress was coming along so I forked your work and released [@hello-pangea/dnd](https://github.com/hello-pangea/dnd) which supports react 18 and strict mode.

Happy to see that you've managed to make it work with react 18! I'll have a look at what you did :slightly_smiling_face: Maybe you've found and fix the issue I was stuck on!

> It would never have been possible without your truly amazing work on the original react-beautiful-dnd. I cannot thank you enough for what you've accomplished here.

It was a lot of late night coding, but it was really fun to do. I've learned so much by migrating the repo from Flow to TypeScript and more. Thank you for this recognition :slightly_smiling_face:

I might try reach you in the upcoming days!

**Comment by 100terres** [comment]
> I might try reach you in the upcoming days!

Hi @Xhale1!

I just send you an email to the gmail address on your GitHub profile page. I sent it from gab@100terres.com.

Let me know if you received it :slightly_smiling_face:

**Comment by 100terres** [comment]
Thanks to @Xhale1 fork :pray: I was able to move forward on some of the blocker I faced. If everything continue to go we'll I might able to release a beta version this weekend!

Here's the new pull request to follow: https://github.com/react-forked/dnd/pull/392

**Comment by AntonOfTheWoods** [comment]
I guess the issue is that it is a bit of a risk, given that there was a very long silence, even after several people offered help. Would you consider having others (like @Xhale1 ) as maintainers on this repo?

**Comment by Xhale1** [comment]
> @100terres  I guess the issue is that it is a bit of a risk, given that there was a very long silence, even after several people offered help. Would you consider having others (like @Xhale1 ) as maintainers on this repo?

@AntonOfTheWoods Gab and I are in touch about maintaining this repo, we'll be providing more details this weekend.

Our current plan is to move this repository to hello-pangea where both he and I will serve as maintainers. I certainly want to help guarantee a strong future for this project 😀

**Comment by 100terres** [comment]
> @100terres I guess the issue is that it is a bit of a risk [...] Would you consider having others (like @Xhale1 ) as maintainers on this repo?

As mentioned by @Xhale1 we'll soon have more details for you :slightly_smiling_face: but this project is not dead yet! :tada: 

There's always a risk in open source development that a project will go un-maintained, but the beauty is that since the code is freely available, so anyone can keep it alive if they have the motivation and the time :slightly_smiling_face:

> given that there was a very long silence

Again sorry to have disappointed you and let you down. It can be difficult to find the right balance between personal life, work and maintaining a complex open source project. I'll do better in the future and I'm sure that with the help of @Xhale1 we'll be able to prevent this situation from happening again.

**Comment by 100terres** [comment]
This [pull request](https://github.com/react-forked/dnd/pull/392) is open (https://github.com/react-forked/dnd/pull/392). It would help, if some of you have the time to do a review :slightly_smiling_face:

It tackles

- https://github.com/react-forked/dnd/issues/317
- https://github.com/react-forked/dnd/issues/320

Once it's merge we'll be ready to release a beta version supporting react 18 and it's new strict mode behavior :slightly_smiling_face:

**Comment by 100terres** [comment]
Beta version released!

https://github.com/react-forked/dnd/releases/tag/v15.0.0-beta.0
https://www.npmjs.com/package/@react-forked/dnd/v/15.0.0-beta.0

**Comment by 100terres** [comment]
Version 15.0.0 is now released! It supports react 18, strict mode and drop ie 11. Have fun!

**Comment by Xhale1** [comment]
@AntonOfTheWoods and others, it's official! @100terres and I are co-maintaining this library as part of the Pangea organization :)

I think y'all will enjoy the results of our consolidated efforts going forward 👍

**Comment by AntonOfTheWoods** [comment]
Thanks very much to both @Xhale1 and @100terres and sorry for the pressure! Now I will definitely be able to avoid going down the react-dnd path. Awesome!

**Comment by AntonOfTheWoods** [comment]
It's confirmed, absolutely flawless, drop in replacement for `react-beautiful-dnd`. You are both legends, thanks!

**Comment by RIP21** [comment]
One last thing that you guys probably need to do to make it 100% compatible with React 18 is to bump dependedncy of `use-memo-one` because this one causes peerDependencies issue in React 18 codebase. 
```
└─┬ @hello-pangea/dnd 16.0.0
  └─┬ use-memo-one 1.1.2
    └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.2.0
```
Version 1.1.3 fixes that.

**Comment by 100terres** [comment]
@RIP21 I've made a new release [`v16.0.1`](https://github.com/hello-pangea/dnd/releases/tag/v16.0.1) should fix the issue you are facing.
